version: '3'
services:
  front-end:
    image: node:16-alpine
    container_name: jordan_front_end
    working_dir: /app
    volumes: 
    - ./front-end:/app
    stdin_open: true
    tty: true
    command: sh
    ports:
    - 5000:3000
    restart: on-failure